### ISSUE TITLE
localhost:8100 not available

### ISSUE THREAD

**Issue by kddc** [mkaag/docker-ionic#1]
Hey I tried your container and for me it didnt work out of the box. I have an ionic project which works with ionic and everything installed on my machine, but it does not, when i try to start the same project with your container.

I started

    docker run -ti \
    -v /path/to/your/ionic-project/:/myApp:rw \
    -p 8100:8100 -p 35729:35729 \
    mkaag/ionic

, but localhost:8100 was not available. I use a Mac. Could that be the problem? Do you have an idea what could be the problem? I'm not too experienced with docker, but i thought using others containers could work.

Thank you very much

**Comment by mkaag** [comment]
Hi Julian,

can you let me know how do you run docker on OSX?

I do use [dinghy](https://github.com/codekitchen/dinghy) on my OSX and explicitly open TCP 8100 on the installed VirtualBox. Then while running `ionic serve` I select the interface mapped to `eth0`. You can from there enable `consolelogs` and `serverlogs` and see if you can reach `http://localhost:8100` from OSX.

Have a try and let me know.
Cheers!
